### ISSUE TITLE
为什么用了你的系统wan口插的网线灯都不亮

### ISSUE THREAD

**Issue by 460077218** [msylgj/R2S-OpenWrt#2]
为什么刷了你的系统之后wan口插了网线灯都不亮，那不是上不了网了，怎么处理

**Comment by 243226114** [comment]
是的是的我也是这样的wan口灯不亮,不知道怎么弄都没有办法上网

**Comment by msylgj** [comment]
README写的很清楚了,wan&lan互换

**Comment by 243226114** [comment]
我知道互换了，就是原价的lan口灯不亮了呀，原来wan直接电脑进去可以设置的，可是我要连网的时候插上网线灯也不亮，就是没有收到信号一样的！这是什么情况！！！！！！
